### ISSUE TITLE
Standardization process

### ISSUE THREAD

**Issue by sgayda2** [aurora-opensource/au#145] opened 2023-07-06 23:35 UTC
Sorry if this is the wrong place or the wrong way to ask, but are there any plans to submit this library or a version of it to be added to the C++ standard library? I know that there was a previous attempt to add something like this to the standard library (P1935) but that seemed to have stalled and stopped. How does this library compare to the previously proposed P1935 (https://github.com/mpusz/mp-units)?

**Comment by chiphogg** [comment] 2023-07-09 22:11
This is a good place/way to ask; thanks for bringing it up!

I see you already got some info in mpusz/mp-units#471.  I can confirm that yes, I'm working with @mpusz and other leading units library authors to try to make a proposal for a standard C++ units library, targeting C++29.

As for Au, I never had any plans to propose it for standardization, and here's why.

One reason is that I couldn't figure out good interfaces.  Au gets a lot of usability/readability mileage out of having only one namespace, and having it be very short.  If we put it into the standard, that's at least `std::` instead of `au::`... but it would probably be much worse, since many of our names (e.g., `std::nano`) are already taken.  I guess the best we could hope for is `std::au::`, but I doubt we'd get it, since `au` isn't very descriptive outside of the context of _a library by that name_ that users explicitly included.  So I assumed we'd get stuck with `std::units::`, which makes for quite a mouthful.

```cpp
// Today's syntax
auto speed = (au::kilo(au::meters) / au::hour)(100);

// Feared syntax
auto speed = (std::units::kilo(std::units::meters) / std::units::hour)(100);
```

Another reason is that due to our emphasis on accessibility --- and the associated constraint to preserve C++14 compatibility --- we can't take advantage of the wealth of new features enabled by the watershed C++20 release.  In particular, both concepts and non-type template parameters (NTTPs) unlock really exciting new possibilities, with big effects on the end user interface.  Any future standard C++ units library should take advantage of the features in the standard at the time that it's proposed.

I think that in some alternative universe, if [`au.hh`](https://aurora-opensource.github.io/au/main/au.hh) were dropped into the C++ community's lap at the start of 2014, we could have added it to C++17, and it would have been a huge benefit: namely, having a widely available standard units library for an extra 12 years.  However, the way it actually turned out, these ideas simply took time to mature, and now we're in a place where it makes more sense to explore what we can do with more cutting edge interfaces like mp-units has.  The benefit of this delay is that the C++29 version of `std::units`, if it gets in, will have better interfaces than it otherwise would have.

The good news is that in making a standard units library, we basically get to cherry pick the best ideas from across the ecosystem.  So, ideas from Au --- such as [magnitudes](https://aurora-opensource.github.io/au/main/reference/magnitude/), and unit-safe interfaces --- have already made their way to mp-units, and are very likely to end up in any standard units library (unless we find something even better!).  And I have high hopes for other concepts: for example, I'd love to see a [`std::zero_t` and `std::zero` object](https://aurora-opensource.github.io/au/main/discussion/concepts/zero/).

I'll close the issue just to keep our board clean, but thanks again for raising it!  We can keep discussing on mpusz/mp-units#471.

**Closed by chiphogg** 2023-07-09 22:11 UTC
